apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.twun.io
    chart: docker-registry
    targetRevision: 2.0.0
    helm:
      values: |-
        ingress:
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          enabled: true
          paths:
            - /
          hosts:
            - registry.172.28.128.32.nip.io
          tls:
            - secretName: registry-tls
              hosts:
                - registry.172.28.128.32.nip.io