apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-cluster
  namespace: kafka-dev
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  # authentication:
  #   type: tls
  #   certificateAndKey:
  #     certificate: user.crt
  #     key: user.key
  #     secretName: kafka-dev-connect
  bootstrapServers: kafka-dev-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-dev-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: kafka-connect-cluster
    offset.storage.topic: kafka-connect-cluster-offsets
    config.storage.topic: kafka-connect-cluster-configs
    status.storage.topic: kafka-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  build:

    output:
      type: docker
      image: viniciussilva/kafka-connect-cluster:latest
      pushSecret: docker-creds
    plugins:
      - name: voluble-connector
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/mdrogalis/voluble/versions/0.3.1/mdrogalis-voluble-0.3.1.zip